In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset)
dataset=dataset.drop(['age','cad_no','pcc_notpresent','ba_notpresent','htn_no','dm_no','appet_poor','pe_poor','ane_no','classification_no'],axis=1)
dataset

,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,...,0,0,0,0,0,0,1,1,0,1
1,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,...,1,0,0,0,0,0,1,0,0,1
2,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,...,1,0,0,0,0,0,1,0,0,1
3,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,...,1,0,0,0,0,0,1,0,1,1
4,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,37.000000,...,1,0,0,0,0,0,1,0,0,1
395,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,27.000000,...,1,0,0,1,1,0,1,0,1,1
396,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,26.000000,...,1,0,0,1,1,0,0,0,0,1
397,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,38.868902,...,1,0,0,1,1,0,1,0,1,1
398,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,53.000000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
dataset.columns

Index(['bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc',
       'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_present', 'ba_present',
       'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes',
       'classification_yes'],
      dtype='object')

In [6]:
independent= dataset[['bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc',
       'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_present', 'ba_present',
       'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
independent

,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,...,pc_abnormal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,...,1,0,0,0,0,0,0,1,1,0
1,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,...,0,1,0,0,0,0,0,1,0,0
2,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,...,0,1,0,0,0,0,0,1,0,0
3,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,...,0,1,0,0,0,0,0,1,0,1
4,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,37.000000,...,0,1,0,0,0,0,0,1,0,0
395,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,27.000000,...,0,1,0,0,1,1,0,1,0,1
396,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,26.000000,...,0,1,0,0,1,1,0,0,0,0
397,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,38.868902,...,0,1,0,0,1,1,0,1,0,1
398,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,53.000000,...,0,1,0,0,0,0,0,1,0,0

In [7]:
dependent= dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =  sc.fit_transform(x_test)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
from sklearn.model_selection import GridSearchCV
grid_parameters = {'solver':['newton-cg','lbfgs','liblinear','saga'],'penalty':['12']}
grid = GridSearchCV(LogisticRegression(),grid_parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:    2.9s remaining:    1.2s

ValueError: Logistic Regression supports only penalties in ['l1', 'l2', 'elasticnet', 'none'], got 12.

In [12]:
from sklearn.svm import SVC

In [13]:
from sklearn.model_selection import GridSearchCV
grid_parameters = {'kernel': ['linear','rbf','poly','sigmoid'],'gamma':['auto','scale'],'C':[10,100,1000,2000,3000]}
grid = GridSearchCV(SVC(probability=True),grid_parameters,refit=True,verbose=3,cv=5,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    3.3s
[Parallel(n_jobs=-1)]: Done 126 out of 200 | elapsed:    3.8s remaining:    2.2s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    4.1s finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [14]:
result = grid.cv_results_
grid_prediction = grid.predict(x_test)